package aplicacion.modelo.dominio;
// Generated 12/06/2019 18:02:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Catalogo generated by hbm2java
 */
public class Catalogo implements java.io.Serializable {

    private Integer idCatalogo;
    private Producto producto;
    private Promocion promocion;
    private String nombre;
    private byte estado;
    private Set ventas = new HashSet(0);

    public Catalogo() {
    }

    public Catalogo(Producto producto, Promocion promocion, byte estado) {
        this.producto = producto;
        this.promocion = promocion;
        this.estado = estado;
    }

    public Catalogo(Producto producto, Promocion promocion, String nombre, byte estado) {
        this.producto = producto;
        this.promocion = promocion;
        this.estado = estado;
    }

    public Catalogo(Producto producto, Promocion promocion, String nombre, byte estado, Set ventas) {
        this.producto = producto;
        this.promocion = promocion;
        this.nombre = nombre;
        this.estado = estado;
        this.ventas = ventas;
    }

    public Integer getIdCatalogo() {
        return this.idCatalogo;
    }

    public void setIdCatalogo(Integer idCatalogo) {
        this.idCatalogo = idCatalogo;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Promocion getPromocion() {
        return this.promocion;
    }

    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public byte getEstado() {
        return this.estado;
    }

    public void setEstado(byte estado) {
        this.estado = estado;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    } 
   
}
