package aplicacion.modelo.dominio;
// Generated 12/06/2019 18:02:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String nombre;
     //private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   // public Set getUsuarios() {
     //   return this.usuarios;
    //}
    
  //  public void setUsuarios(Set usuarios) {
    //    this.usuarios = usuarios;
    //}

    



}


