package aplicacion.modelo.dominio;
// Generated 12/06/2019 18:02:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private TipoUsuario tipoUsuario;
     private String nombre;
     private String apellido;
     private String username;
     private String password;
     private String correo;
     private String dni;
     private Date fechaDeNacimiento;
     private byte estado;
     private Set ventasForIdCliente = new HashSet(0);
     private Set ventasForIdVendedor = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }public Usuario(TipoUsuario tipoUsuario, String nombre, String apellido, String username, String password, String correo, String dni, Date fechaDeNacimiento, byte estado) {
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.username = username;
       this.password = password;
       this.correo = correo;
       this.dni = dni;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.estado = estado;
    }
    public Usuario(TipoUsuario tipoUsuario, String nombre, String apellido, String username, String password, String correo, String dni, Date fechaDeNacimiento, byte estado, Set ventasForIdCliente, Set ventasForIdVendedor) {
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.username = username;
       this.password = password;
       this.correo = correo;
       this.dni = dni;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.estado = estado;
       this.ventasForIdCliente = ventasForIdCliente;
       this.ventasForIdVendedor = ventasForIdVendedor;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Set getVentasForIdCliente() {
        return this.ventasForIdCliente;
    }
    
    public void setVentasForIdCliente(Set ventasForIdCliente) {
        this.ventasForIdCliente = ventasForIdCliente;
    }
    public Set getVentasForIdVendedor() {
        return this.ventasForIdVendedor;
    }
    
    public void setVentasForIdVendedor(Set ventasForIdVendedor) {
        this.ventasForIdVendedor = ventasForIdVendedor;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", tipoUsuario=" + tipoUsuario + ", nombre=" + nombre + ", apellido=" + apellido + ", username=" + username + ", password=" + password + ", correo=" + correo + ", dni=" + dni + ", fechaDeNacimiento=" + fechaDeNacimiento + ", estado=" + estado + ", ventasForIdCliente=" + ventasForIdCliente + ", ventasForIdVendedor=" + ventasForIdVendedor + '}';
    }




}


