package aplicacion.modelo.dominio;
// Generated 12/06/2019 18:02:32 by Hibernate Tools 4.3.1



/**
 * VentaProducto generated by hbm2java
 */
public class VentaProducto  implements java.io.Serializable {


     private Integer idVentaProducto;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private Double total;

    public VentaProducto() {
    }

	
    public VentaProducto(Producto producto, Venta venta) {
        this.producto = producto;
        this.venta = venta;
    }
    public VentaProducto(Producto producto, Venta venta, Integer cantidad, Double total) {
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public Integer getIdVentaProducto() {
        return this.idVentaProducto;
    }
    
    public void setIdVentaProducto(Integer idVentaProducto) {
        this.idVentaProducto = idVentaProducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


