package aplicacion.hibernate.mapeos;
// Generated 08/06/2019 20:22:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Almacen almacen;
     private TipoHelado tipoHelado;
     private String nombre;
     private String descripcion;
     private Double precio;
     private int tipoHelado_1;
     private byte estado;
     private Set ventaProductos = new HashSet(0);
     private Set catalogos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Almacen almacen, int tipoHelado_1, byte estado) {
        this.almacen = almacen;
        this.tipoHelado_1 = tipoHelado_1;
        this.estado = estado;
    }
    public Producto(Almacen almacen, TipoHelado tipoHelado, String nombre, String descripcion, Double precio, int tipoHelado_1, byte estado, Set ventaProductos, Set catalogos) {
       this.almacen = almacen;
       this.tipoHelado = tipoHelado;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.tipoHelado_1 = tipoHelado_1;
       this.estado = estado;
       this.ventaProductos = ventaProductos;
       this.catalogos = catalogos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public TipoHelado getTipoHelado() {
        return this.tipoHelado;
    }
    
    public void setTipoHelado(TipoHelado tipoHelado) {
        this.tipoHelado = tipoHelado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public int getTipoHelado_1() {
        return this.tipoHelado_1;
    }
    
    public void setTipoHelado_1(int tipoHelado_1) {
        this.tipoHelado_1 = tipoHelado_1;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Set getVentaProductos() {
        return this.ventaProductos;
    }
    
    public void setVentaProductos(Set ventaProductos) {
        this.ventaProductos = ventaProductos;
    }
    public Set getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(Set catalogos) {
        this.catalogos = catalogos;
    }




}


