package aplicacion.hibernate.mapeos;
// Generated 08/06/2019 20:22:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private Catalogo catalogo;
     private Usuario usuarioByCliente;
     private Usuario usuarioByVendedor;
     private String fecha;
     private Set ventaProductos = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idVenta, Catalogo catalogo, Usuario usuarioByCliente, Usuario usuarioByVendedor) {
        this.idVenta = idVenta;
        this.catalogo = catalogo;
        this.usuarioByCliente = usuarioByCliente;
        this.usuarioByVendedor = usuarioByVendedor;
    }
    public Venta(int idVenta, Catalogo catalogo, Usuario usuarioByCliente, Usuario usuarioByVendedor, String fecha, Set ventaProductos) {
       this.idVenta = idVenta;
       this.catalogo = catalogo;
       this.usuarioByCliente = usuarioByCliente;
       this.usuarioByVendedor = usuarioByVendedor;
       this.fecha = fecha;
       this.ventaProductos = ventaProductos;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Usuario getUsuarioByCliente() {
        return this.usuarioByCliente;
    }
    
    public void setUsuarioByCliente(Usuario usuarioByCliente) {
        this.usuarioByCliente = usuarioByCliente;
    }
    public Usuario getUsuarioByVendedor() {
        return this.usuarioByVendedor;
    }
    
    public void setUsuarioByVendedor(Usuario usuarioByVendedor) {
        this.usuarioByVendedor = usuarioByVendedor;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public Set getVentaProductos() {
        return this.ventaProductos;
    }
    
    public void setVentaProductos(Set ventaProductos) {
        this.ventaProductos = ventaProductos;
    }




}


