package aplicacion.hibernate.mapeos.desdeclase;
// Generated 08/06/2019 20:22:06 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.*;
import aplicacion.modelo.dominio.TipoHelado;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Almacen almacen;
     private TipoHelado tipoHelado;
     private String nombre;
     private String descripcion;
     private Double precio;
     private boolean estado;

    public Producto() {
    }


    public Producto(Almacen almacen, TipoHelado tipoHelado, String nombre, String descripcion, Double precio,boolean estado) {
       this.almacen = almacen;
       this.tipoHelado = tipoHelado;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.estado = estado;
       }
    
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public TipoHelado getTipoHelado() {
        return this.tipoHelado;
    }
    
    public void setTipoHelado(TipoHelado tipoHelado) {
        this.tipoHelado = tipoHelado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
   
    public boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
   
}


