package aplicacion.hibernate.mapeos.desdeclase;
// Generated 08/06/2019 20:22:06 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String nombre;

    public TipoUsuario() {
    }

    public TipoUsuario(String nombre, Set usuarios) {
       this.nombre = nombre;
    }
   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}


