package aplicacion.hibernate.mapeos.desdeclase;
// Generated 08/06/2019 20:22:06 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private Catalogo catalogo;
     private Usuario cliente;
     private Usuario vendedor;
     private Date fecha;

    public Venta() {
    }

	
    public Venta(int idVenta, Catalogo catalogo, Usuario cliente, Usuario vendedor, Date fecha) {
        this.idVenta = idVenta;
        this.catalogo = catalogo;
        this.cliente = cliente;
        this.vendedor = vendedor;
        this.fecha = fecha;
    }
    
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Usuario cliente() {
        return this.cliente;
    }
    
    public void cliente(Usuario cliente) {
        this.cliente = cliente;
    }
    public Usuario vendedor() {
        return this.vendedor;
    }
    
    public void vendedor(Usuario vendedor) {
        this.vendedor = vendedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}


